name: README.pretty

on:
  schedule:
    - cron: "0 */24 * * *"
  workflow_dispatch:

jobs:
  prettify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout current repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install src/requirements.txt

      - name: Prettify!
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ github.repository_owner }}
        run: python src/pretty.py

      - name: Checkout profile repo
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository_owner }}/${{ github.repository_owner }}
          token: ${{ secrets.GITHUB_TOKEN }}
          path: profile
      
      - name: Generate README
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ github.repository_owner }}
        run:
          cd profile
          python ../src/pretty.py
      
      - name: Commit changes
        run:
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          
          git add README.md
          git diff --staged --quiet || git commit -m "Update README with latest activity!"
          git push
